parameters:
    Bilan_Social.ContactBundle.Services.Contact.class:  Bilan_Social\Bundle\ContactBundle\Services\Contact

services:
   Bilan_Social.ContactBundle.Services.Contact:
        class:  '%Bilan_Social.ContactBundle.Services.Contact.class%'
        arguments:  ["@mailer", "@doctrine.orm.entity_manager", "@security.token_storage", "@service_container"]