edit.collectivite.listener:
    class: Bilan_Social\Bundle\CollectiviteBundle\Listener\EditCollectiviteListener
    arguments:
        - '@security.authorization_checker'
    tags:
        - { name: doctrine.event_listener, event: preUpdate }
        - { name: doctrine.event_listener, event: postFlush }