import_homepage:
    path:     /
    defaults: { _controller: ImportBundle:Default:index }

import_send_file:
    path:     /api/n4ds/file
    defaults: { _controller: "ImportBundle:Import:Import" }
    methods:  [POST,GET]
    options:
          expose: true

get_whitelist:
    path:     /api/n4ds/whitelist
    defaults: { _controller: "ImportBundle:Import:GetWhiteList" }
    methods:  [GET]
    options:
      expose: true

saved_old_data:
    path:     /api/n4ds/savedOldData
    defaults: { _controller: "ImportBundle:Import:SavedOldData" }
    methods:  [GET, POST]
    options:
        expose: true