# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    entity.campagne:     'Bilan_Social\Bundle\CampagneBundle\Entity\Campagne'
    entity.collectivite:     'Bilan_Social\Bundle\CollectiviteBundle\Entity\Collectivite'
    entity.cdg:     'Bilan_Social\Bundle\CollectiviteBundle\Entity\Cdg'
    entity.user: 'Bilan_Social\Bundle\UserBundle\Entity\User'
    entity.Enquete: 'Bilan_Social\Bundle\EnqueteBundle\Entity\Enquete'
    entity.Departement: 'Bilan_Social\Bundle\CollectiviteBundle\Entity\Departement'
    entity.QuestionCollectiviteConsolide: 'Bilan_Social\Bundle\ConsoBundle\Entity\QuestionCollectiviteConsolide'
    entity.consolide: 'Bilan_Social\Bundle\ConsoBundle\Entity\BilanSocialConsolide'
    entity.EnqueteCollectivite: 'Bilan_Social\Bundle\EnqueteBundle\Entity\EnqueteCollectivite'
    entity.InformationGenerale: 'Bilan_Social\Bundle\ApaBundle\Entity\InformationGenerale'
    entity.InformationCollectiviteAgent: 'Bilan_Social\Bundle\ApaBundle\Entity\InformationColectiviteAgent'
    entity.InitBilanSocial: 'Bilan_Social\Bundle\BilanSocialBundle\Entity\InitBilanSocial'
    entity.ModeleAnalyse: 'Bilan_Social\Bundle\AnalyseBundle\Entity\ModeleAnalyse'
    entity.UtilisateurCdg: 'Bilan_Social\Bundle\UserBundle\Entity\UtilisateurCdg'
    entity.UtilisateurDroits: 'Bilan_Social\Bundle\UserBundle\Entity\UtilisateurDroits'
    entity.question: 'Bilan_Social\Bundle\FaqBundle\Entity\Question'
    Bilan_Social.UserBundle.Component.Authentication.Handler.login_success_handler.class:  'Bilan_Social\Bundle\UserBundle\Component\Authentication\Handler\LoginSuccessHandler'
services:
    bilan_social.security.voter.social:
        class: Bilan_Social\Bundle\UserBundle\Security\SocialVoter
        tags:
            - { name: security.voter }
    enquete.form.flow.create:
        class: Bilan_Social\Bundle\EnqueteBundle\Form\CreateEnqueteFlow
        arguments: ["@doctrine.orm.entity_manager","@security.token_storage"]
        parent: craue.form.flow
    campagne.form.flow.create:
        class: Bilan_Social\Bundle\CampagneBundle\Form\CreateCampagneFlow
        parent: craue.form.flow
    password_controller:
        class: Bilan_Social\Bundle\EnqueteBundle\Controller\PasswordController
        arguments: [ "@doctrine.orm.entity_manager", "@service_container" ]
    analyse_controller:
        class: Bilan_Social\Bundle\AnalyseBundle\Controller\DefaultController
        arguments: [ "@doctrine.orm.entity_manager", "@service_container" ]
        autowire: true
        autoconfigure: true
    Bilan_Social\Bundle\AnalyseBundle\Controller\DefaultController: '@analyse_controller'
    campagne_service:
        class: Bilan_Social\Bundle\CampagneBundle\Repository\CampagneRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - '%entity.campagne%'

    collectivite_consolide_service:
        class: Bilan_Social\Bundle\ConsoBundle\Repository\QuestionCollectiviteConsolideRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - '%entity.QuestionCollectiviteConsolide%'

    consolide_service:
        class: Bilan_Social\Bundle\ConsoBundle\Repository\BilanSocialConsolideRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - '%entity.consolide%'

    user_collectivite:
        class: Bilan_Social\Bundle\CollectiviteBundle\Repository\CollectiviteRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - '%entity.collectivite%'
            
    question_collectivite:
        class: Bilan_Social\Bundle\FaqBundle\Repository\QuestionRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - '%entity.question%'
            
    user_cdg:
        class: Bilan_Social\Bundle\CollectiviteBundle\Repository\CdgRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - '%entity.cdg%'
    
    utilisateur_cdg:
        class: Bilan_Social\Bundle\UserBundle\Repository\UtilisateurCdg
        factory: ["@doctrine", getRepository]
        arguments:
            - '%entity.UtilisateurCdg%'
    
    utilisateur_droits:
        class: Bilan_Social\Bundle\UserBundle\Repository\UtilisateurDroits
        factory: ["@doctrine", getRepository]
        arguments:
            - '%entity.UtilisateurDroits%'
    
    enquete_Collectivite:
        class: Bilan_Social\Bundle\EnqueteBundle\Repository\EnqueteCollectiviteRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - '%entity.EnqueteCollectivite%'

    current_enquete:
        class: Bilan_Social\Bundle\EnqueteBundle\Repository\EnqueteRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - '%entity.Enquete%'
            
    current_enquete_departement:
        class: Bilan_Social\Bundle\CollectiviteBundle\Repository\DepartementRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - '%entity.Departement%'

    information_generale_agent:
        class: Bilan_Social\Bundle\ApaBundle\Repository\InformationGeneraleRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - '%entity.InformationGenerale%'

    information_collectivite_agent:
        class: Bilan_Social\Bundle\ApaBundle\Repository\InformationColectiviteRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - '%entity.InformationCollectiviteAgent%'

    information_bilansocial_saisie:
        class: Bilan_Social\Bundle\BilanSocialBundle\Repository\InitBilanSocialRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - '%entity.InitBilanSocial%'

    edit.collectivite.listener:
        class: Bilan_Social\Bundle\CollectiviteBundle\Listener\EditCollectiviteListener
        arguments:
            - '@security.authorization_checker'
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postFlush }


    Bilan_Social.UserBundle.Component.Authentication.Handler.login_success_handler:
        class:  '%Bilan_Social.UserBundle.Component.Authentication.Handler.login_success_handler.class%'
        arguments:  ["@router","@doctrine.orm.entity_manager","@service_container","@session",  getRepository ]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
            
    dpolac.twig_lambda.extension:
        class: DPolac\TwigLambda\LambdaExtension
        tags: [ { name: twig.extension } ]
        
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
            
    sonata.admin.exporter:
        class: Bilan_Social\Bundle\CollectiviteBundle\Exporter\Exporter

    modele_analyse_service:
        class: Bilan_Social\Bundle\AnalyseBundle\Repository\ModeleAnalyseRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - '%entity.ModeleAnalyse%'
#    snc_second_level_cache:
#        class: '%snc_redis.doctrine_cache_predis.class%'
#        arguments: [ '@snc_redis.default' ]
    userbundle_logoutlistener:
        class: Bilan_Social\Bundle\UserBundle\Listener\LogoutListener

    html_purified_form_transformer:
        class: Exercise\HTMLPurifierBundle\Form\HTMLPurifierTransformer
        arguments:  ['@exercise_html_purifier.default']
        autowire: true
    purified_text_type:
        class: Bilan_Social\Bundle\CoreBundle\Form\PurifiedTextType
        arguments:  ['@html_purified_form_transformer']
        tags: [form.type]
        autowire: true
    Bilan_Social\Bundle\CoreBundle\Form\PurifiedTextType: '@purified_text_type'
    purified_textarea_type:
        class: Bilan_Social\Bundle\CoreBundle\Form\PurifiedTextareaType
        arguments:  ['@html_purified_form_transformer']
        tags: [form.type]
        autowire: true
    Bilan_Social\Bundle\CoreBundle\Form\PurifiedTextareaType: '@purified_textarea_type'
    purified_number_type:
        class: Bilan_Social\Bundle\CoreBundle\Form\PurifiedNumberType
        arguments:  ['@html_purified_form_transformer']
        tags: [form.type]
        autowire: true
    Bilan_Social\Bundle\CoreBundle\Form\PurifiedNumberType: '@purified_number_type'
    bs_conso_ind_preparator:
        class: Bilan_Social\Bundle\ConsoBundle\Services\BsConsoIndPreparator
        arguments: ["@doctrine.orm.entity_manager","@security.token_storage"]

    bs_conso_precedent_preparator:
        class: Bilan_Social\Bundle\ConsoBundle\Services\BsConsoPrecedentPreparator
        arguments: ["@doctrine.orm.entity_manager","@security.token_storage"]
        public: true

    bdd_connection_preparator:
        class: Bilan_Social\Bundle\CoreBundle\Services\BddConnectionPreparator
        arguments: ["@doctrine.orm.entity_manager","@security.token_storage"]
        public: true
        
    dgcl_service_user:
        class: Bilan_Social\Bundle\UserBundle\Validator\Constraints\ConstraintDGCLValidator
        arguments: ["@security.token_storage"]
        tags:
            - name: "validator.constraint_validator"
              alias: "dgcl_constraint_validator"
    check_droit_service:
        class: Bilan_Social\Bundle\ReferencielBundle\Services\CheckDroits
        arguments: ["@security.token_storage"]
        autowire: true

    bilan_social_config_finder:
        class: 'Bilan_Social\Bundle\BilanSocialBundle\Services\ConfigFinder'
        public: true
        autowire: true

    app.entrypoint_key:
        class: 'Bilan_Social\Bundle\CoreBundle\Controller\GpeecEntryPoint'
        arguments:
            - '%app.entrypoint_key%'

    Bilan_Social\Bundle\CoreBundle\Controller\GpeecEntryPoint:
        arguments:
            - '@app.entrypoint_key'
            - '@app.gpeec_entrypoint_url'

    app.gpeec_entrypoint_url:
        class: 'Bilan_Social\Bundle\CoreBundle\Controller\GpeecEntryPoint'
        arguments:
            - '%app.gpeec_entrypoint_url%'

